development:
  adapter: postgresql
  database: theetr_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: theetr_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: theetr_production
  pool: 5
  timeout: 5000